name: deploy stripe-checkout to lambda
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    paths:
      - stripe-checkout.py
    branches:
      - main

jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: stripe-checkout
          source: stripe-checkout/lambda_function.py